name: ${project.name}
version: ${project.version}
description: '{"commit_id": "${git.commit.id.abbrev}", "commit_time": "${git.commit.time}"}'
main: pl.daffit.enginex.EngineX
author: Daffit
commands: {}